/**
 * Texture atlas builder.
 *
 * Produces a 192×16 pixel canvas atlas with 12 tiles (16×16 px each).
 * All tiles are loaded from src/assets/textures/block/ PNG files.
 *
 * Tile layout (left → right):
 *   0 = grass_block_top   1 = grass_block_side   2 = dirt          3 = stone
 *   4 = coal_ore          5 = iron_ore           6 = gold_ore       7 = diamond_ore
 *   8 = emerald_ore       9 = lapis_ore         10 = redstone_ore  11 = copper_ore
 *
 * Base textures are generated by:  bun scripts/gen-base-textures.ts
 */

import coalOreUrl from "~/assets/textures/block/coal_ore.png";
import copperOreUrl from "~/assets/textures/block/copper_ore.png";
import diamondOreUrl from "~/assets/textures/block/diamond_ore.png";
import dirtUrl from "~/assets/textures/block/dirt.png?inline";
import emeraldOreUrl from "~/assets/textures/block/emerald_ore.png";
import goldOreUrl from "~/assets/textures/block/gold_ore.png";
import grassSideUrl from "~/assets/textures/block/grass_block_side.png?inline";
import grassTopUrl from "~/assets/textures/block/grass_block_top.png?inline";
import ironOreUrl from "~/assets/textures/block/iron_ore.png";
import lapisOreUrl from "~/assets/textures/block/lapis_ore.png";
import redstoneOreUrl from "~/assets/textures/block/redstone_ore.png";
import stoneUrl from "~/assets/textures/block/stone.png?inline";

// Ordered by tile index 0–11.
export const ATLAS_TILE_NAMES = [
  "grass_block_top",
  "grass_block_side",
  "dirt",
  "stone",
  "coal_ore",
  "iron_ore",
  "gold_ore",
  "diamond_ore",
  "emerald_ore",
  "lapis_ore",
  "redstone_ore",
  "copper_ore",
] as const;

export type AtlasTileName = (typeof ATLAS_TILE_NAMES)[number];

const DEFAULT_ALBEDO_URLS: Record<AtlasTileName, string> = {
  grass_block_top: grassTopUrl,
  grass_block_side: grassSideUrl,
  dirt: dirtUrl,
  stone: stoneUrl,
  coal_ore: coalOreUrl,
  iron_ore: ironOreUrl,
  gold_ore: goldOreUrl,
  diamond_ore: diamondOreUrl,
  emerald_ore: emeraldOreUrl,
  lapis_ore: lapisOreUrl,
  redstone_ore: redstoneOreUrl,
  copper_ore: copperOreUrl,
};

// Kept for backwards compatibility with the legacy build path.
const TILE_URLS = ATLAS_TILE_NAMES.map((name) => DEFAULT_ALBEDO_URLS[name]);

export interface AtlasSourceManifest {
  albedo?: Partial<Record<AtlasTileName, string>>;
  normal?: Partial<Record<AtlasTileName, string>>;
  specular?: Partial<Record<AtlasTileName, string>>;
}

export interface AtlasBuildStats {
  albedoFallbacks: number;
  normalFallbacks: number;
  specularFallbacks: number;
}

export const ATLAS_TILES = 12;
const T = 16; // tile size in pixels

function loadImage(url: string): Promise<HTMLImageElement> {
  return new Promise((resolve, reject) => {
    const img = new Image();
    img.onload = () => resolve(img);
    img.onerror = () => reject(new Error(`Failed to load texture: ${url}`));
    img.src = url;
  });
}

async function loadImageSafe(url: string): Promise<HTMLImageElement | null> {
  try {
    return await loadImage(url);
  } catch {
    return null;
  }
}

function createAtlasCanvas(): {
  canvas: HTMLCanvasElement;
  ctx: CanvasRenderingContext2D;
} {
  const W = T * ATLAS_TILES;
  const canvas = document.createElement("canvas");
  canvas.width = W;
  canvas.height = T;
  const ctx = canvas.getContext("2d")!;
  ctx.imageSmoothingEnabled = false;
  return { canvas, ctx };
}

function drawSolidTile(
  ctx: CanvasRenderingContext2D,
  tileIndex: number,
  color: string,
): void {
  ctx.fillStyle = color;
  ctx.fillRect(tileIndex * T, 0, T, T);
}

function drawSolidTileRGBA(
  ctx: CanvasRenderingContext2D,
  tileIndex: number,
  rgba: [number, number, number, number],
): void {
  const [r, g, b, a] = rgba;
  const img = ctx.getImageData(tileIndex * T, 0, T, T);
  const d = img.data;
  for (let i = 0; i < d.length; i += 4) {
    d[i] = r;
    d[i + 1] = g;
    d[i + 2] = b;
    d[i + 3] = a;
  }
  ctx.putImageData(img, tileIndex * T, 0);
}

/**
 * Builds the 192×16 pixel atlas canvas (shared by WebGL and WebGPU paths).
 * Tiles are loaded from PNG assets and drawn in tile-index order.
 */
export async function buildAtlasCanvas(): Promise<HTMLCanvasElement> {
  const { canvas, ctx } = createAtlasCanvas();
  const images = await Promise.all(TILE_URLS.map(loadImage));
  for (let i = 0; i < images.length; i++) {
    ctx.drawImage(images[i], i * T, 0, T, T);
  }
  return canvas;
}

/**
 * Builds a 192×16 flat-normal atlas: every pixel = (128, 128, 255, 255).
 *
 * Encodes the labPBR _n convention:
 *   R=128 → tangent-space X = 0  (no horizontal slope)
 *   G=128 → tangent-space Y = 0  (no horizontal slope)
 *   B=255 → AO = 1.0             (fully unoccluded)
 *   A=255 → height = 1.0         (max parallax)
 *
 * Used as the default normal atlas when no _n PBR textures are available.
 */
export function buildNormalAtlasCanvas(): HTMLCanvasElement {
  const { canvas, ctx } = createAtlasCanvas();
  for (let i = 0; i < ATLAS_TILES; i++) {
    drawSolidTile(ctx, i, "rgb(128,128,255)");
  }
  return canvas;
}

/**
 * Builds a 192×16 default-specular atlas: every pixel = (0, 25, 0, 255).
 *
 * Encodes the labPBR _s convention:
 *   R=0   → smoothness = 0    (fully rough, no specular highlights)
 *   G=25  → F0 ≈ 10 %         (dielectric, maps to ~0.04 base reflectance)
 *   B=0   → porosity/SSS = 0
 *   A=0   → emissive = 0
 *
 * Used as the default specular atlas when no _s PBR textures are available.
 */
export function buildSpecularAtlasCanvas(): HTMLCanvasElement {
  const { canvas, ctx } = createAtlasCanvas();
  for (let i = 0; i < ATLAS_TILES; i++) {
    drawSolidTileRGBA(ctx, i, [0, 25, 0, 0]);
  }
  return canvas;
}

async function buildManifestAlbedoAtlas(
  manifest?: AtlasSourceManifest,
): Promise<{
  canvas: HTMLCanvasElement;
  fallbacks: number;
}> {
  const { canvas, ctx } = createAtlasCanvas();
  let fallbacks = 0;
  const hasManifest = Boolean(manifest?.albedo);

  for (let i = 0; i < ATLAS_TILE_NAMES.length; i++) {
    const name = ATLAS_TILE_NAMES[i];
    const overrideUrl = manifest?.albedo?.[name];
    const defaultUrl = DEFAULT_ALBEDO_URLS[name];

    let img: HTMLImageElement | null = null;
    if (overrideUrl) {
      img = await loadImageSafe(overrideUrl);
      if (!img) {
        fallbacks++;
      }
    } else if (hasManifest) {
      // Manifest exists but this tile is missing in it.
      fallbacks++;
    }

    if (!img) {
      img = await loadImageSafe(defaultUrl);
    }
    if (!img) {
      throw new Error(
        `Failed to load required albedo texture for tile: ${name}`,
      );
    }

    ctx.drawImage(img, i * T, 0, T, T);
  }

  return { canvas, fallbacks };
}

async function buildManifestChannelAtlas(
  channel: "normal" | "specular",
  manifest?: AtlasSourceManifest,
): Promise<{
  canvas: HTMLCanvasElement;
  fallbacks: number;
}> {
  const { canvas, ctx } = createAtlasCanvas();
  let fallbacks = 0;
  const hasManifest = Boolean(manifest?.[channel]);
  const fallbackColor =
    channel === "normal" ? "rgb(128,128,255)" : null;

  for (let i = 0; i < ATLAS_TILE_NAMES.length; i++) {
    const name = ATLAS_TILE_NAMES[i];
    const overrideUrl = manifest?.[channel]?.[name];
    let img: HTMLImageElement | null = null;

    if (overrideUrl) {
      img = await loadImageSafe(overrideUrl);
      if (!img) fallbacks++;
    } else if (hasManifest) {
      // Manifest channel exists but this tile is missing.
      fallbacks++;
    }

    if (img) {
      ctx.drawImage(img, i * T, 0, T, T);
    } else {
      if (channel === "normal") {
        drawSolidTile(ctx, i, fallbackColor!);
      } else {
        drawSolidTileRGBA(ctx, i, [0, 25, 0, 0]);
      }
    }
  }

  return { canvas, fallbacks };
}

/**
 * Builds all three atlas canvases (albedo, normal, specular) concurrently.
 * The albedo atlas loads PNG assets asynchronously; the normal and specular
 * atlases are generated programmatically and resolve synchronously.
 */
export async function buildAllAtlases(): Promise<{
  albedo: HTMLCanvasElement;
  normal: HTMLCanvasElement;
  specular: HTMLCanvasElement;
  stats: AtlasBuildStats;
}> {
  const albedo = await buildAtlasCanvas();
  return {
    albedo,
    normal: buildNormalAtlasCanvas(),
    specular: buildSpecularAtlasCanvas(),
    stats: {
      albedoFallbacks: 0,
      normalFallbacks: 0,
      specularFallbacks: 0,
    },
  };
}

export async function buildAllAtlasesFromManifest(
  manifest?: AtlasSourceManifest,
): Promise<{
  albedo: HTMLCanvasElement;
  normal: HTMLCanvasElement;
  specular: HTMLCanvasElement;
  stats: AtlasBuildStats;
}> {
  const [albedoRes, normalRes, specularRes] = await Promise.all([
    buildManifestAlbedoAtlas(manifest),
    buildManifestChannelAtlas("normal", manifest),
    buildManifestChannelAtlas("specular", manifest),
  ]);

  return {
    albedo: albedoRes.canvas,
    normal: normalRes.canvas,
    specular: specularRes.canvas,
    stats: {
      albedoFallbacks: albedoRes.fallbacks,
      normalFallbacks: normalRes.fallbacks,
      specularFallbacks: specularRes.fallbacks,
    },
  };
}
