/**
 * Texture atlas builder.
 *
 * Produces a 192×16 pixel canvas atlas with 12 tiles (16×16 px each).
 * All tiles are loaded from src/assets/textures/block/ PNG files.
 *
 * Tile layout (left → right):
 *   0 = grass_block_top   1 = grass_block_side   2 = dirt          3 = stone
 *   4 = coal_ore          5 = iron_ore           6 = gold_ore       7 = diamond_ore
 *   8 = emerald_ore       9 = lapis_ore         10 = redstone_ore  11 = copper_ore
 *
 * ATLAS_TILES must stay in sync with voxel_VERTEXSHADER.glsl.
 * Base textures are generated by:  bun scripts/gen-base-textures.ts
 */

// Vite resolves these to hashed asset URLs at build time.
import grassTopUrl from "./assets/textures/block/grass_block_top.png";
import grassSideUrl from "./assets/textures/block/grass_block_side.png";
import dirtUrl from "./assets/textures/block/dirt.png";
import stoneUrl from "./assets/textures/block/stone.png";
import coalOreUrl from "./assets/textures/block/coal_ore.png";
import ironOreUrl from "./assets/textures/block/iron_ore.png";
import goldOreUrl from "./assets/textures/block/gold_ore.png";
import diamondOreUrl from "./assets/textures/block/diamond_ore.png";
import emeraldOreUrl from "./assets/textures/block/emerald_ore.png";
import lapisOreUrl from "./assets/textures/block/lapis_ore.png";
import redstoneOreUrl from "./assets/textures/block/redstone_ore.png";
import copperOreUrl from "./assets/textures/block/copper_ore.png";

// Ordered by tile index 0–11.
const TILE_URLS = [
  grassTopUrl, // 0
  grassSideUrl, // 1
  dirtUrl, // 2
  stoneUrl, // 3
  coalOreUrl, // 4
  ironOreUrl, // 5
  goldOreUrl, // 6
  diamondOreUrl, // 7
  emeraldOreUrl, // 8
  lapisOreUrl, // 9
  redstoneOreUrl, // 10
  copperOreUrl, // 11
];

export const ATLAS_TILES = 12;
const T = 16; // tile size in pixels

function loadImage(url: string): Promise<HTMLImageElement> {
  return new Promise((resolve, reject) => {
    const img = new Image();
    img.onload = () => resolve(img);
    img.onerror = () => reject(new Error(`Failed to load texture: ${url}`));
    img.src = url;
  });
}

/**
 * Builds the 192×16 pixel atlas canvas (shared by WebGL and WebGPU paths).
 * Tiles are loaded from PNG assets and drawn in tile-index order.
 */
export async function buildAtlasCanvas(): Promise<HTMLCanvasElement> {
  const W = T * ATLAS_TILES; // 192 px
  const canvas = document.createElement("canvas");
  canvas.width = W;
  canvas.height = T;
  const ctx = canvas.getContext("2d")!;
  ctx.imageSmoothingEnabled = false;
  const images = await Promise.all(TILE_URLS.map(loadImage));
  for (let i = 0; i < images.length; i++) {
    ctx.drawImage(images[i], i * T, 0, T, T);
  }
  return canvas;
}

/**
 * Builds a 192×16 flat-normal atlas: every pixel = (128, 128, 255, 255).
 *
 * Encodes the labPBR _n convention:
 *   R=128 → tangent-space X = 0  (no horizontal slope)
 *   G=128 → tangent-space Y = 0  (no horizontal slope)
 *   B=255 → AO = 1.0             (fully unoccluded)
 *   A=255 → height = 1.0         (max parallax)
 *
 * Used as the default normal atlas when no _n PBR textures are available.
 */
export function buildNormalAtlasCanvas(): HTMLCanvasElement {
  const W = T * ATLAS_TILES;
  const canvas = document.createElement("canvas");
  canvas.width = W;
  canvas.height = T;
  const ctx = canvas.getContext("2d")!;
  // rgba(128,128,255,255) = flat normal pointing straight out, full AO
  ctx.fillStyle = "rgb(128,128,255)";
  ctx.fillRect(0, 0, W, T);
  return canvas;
}

/**
 * Builds a 192×16 default-specular atlas: every pixel = (0, 25, 0, 255).
 *
 * Encodes the labPBR _s convention:
 *   R=0   → smoothness = 0    (fully rough, no specular highlights)
 *   G=25  → F0 ≈ 10 %         (dielectric, maps to ~0.04 base reflectance)
 *   B=0   → porosity/SSS = 0
 *   A=0   → emissive = 0
 *
 * Used as the default specular atlas when no _s PBR textures are available.
 */
export function buildSpecularAtlasCanvas(): HTMLCanvasElement {
  const W = T * ATLAS_TILES;
  const canvas = document.createElement("canvas");
  canvas.width = W;
  canvas.height = T;
  const ctx = canvas.getContext("2d")!;
  ctx.fillStyle = "rgb(0,25,0)";
  ctx.fillRect(0, 0, W, T);
  return canvas;
}

/**
 * Builds all three atlas canvases (albedo, normal, specular) concurrently.
 * The albedo atlas loads PNG assets asynchronously; the normal and specular
 * atlases are generated programmatically and resolve synchronously.
 */
export async function buildAllAtlases(): Promise<{
  albedo:   HTMLCanvasElement;
  normal:   HTMLCanvasElement;
  specular: HTMLCanvasElement;
}> {
  const albedo = await buildAtlasCanvas();
  return { albedo, normal: buildNormalAtlasCanvas(), specular: buildSpecularAtlasCanvas() };
}

/**
 * Builds and uploads a 192×16 texture atlas asynchronously.
 * All 12 PNG tiles are fetched in parallel and drawn onto a canvas strip.
 *
 * UNPACK_FLIP_Y maps canvas row-0 (image top) to UV v=1 (face top).
 */
export async function createAtlasTexture(
  gl: WebGL2RenderingContext,
): Promise<WebGLTexture | null> {
  const canvas = await buildAtlasCanvas();

  // ── Upload to WebGL ──────────────────────────────────────────
  const tex = gl.createTexture();
  gl.bindTexture(gl.TEXTURE_2D, tex);
  gl.pixelStorei(gl.UNPACK_FLIP_Y_WEBGL, true);
  gl.texImage2D(gl.TEXTURE_2D, 0, gl.RGBA, gl.RGBA, gl.UNSIGNED_BYTE, canvas);
  gl.pixelStorei(gl.UNPACK_FLIP_Y_WEBGL, false);
  gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MIN_FILTER, gl.NEAREST);
  gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MAG_FILTER, gl.NEAREST);
  gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_WRAP_S, gl.CLAMP_TO_EDGE);
  gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_WRAP_T, gl.CLAMP_TO_EDGE);
  return tex;
}
